# Generated by Django 2.2.6 on 2020-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0003_auto_20200522_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_foo.png', upload_to='post_picture'),
        ),
    ]
