# Generated by Django 2.2.6 on 2020-06-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0008_checkmask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkmask',
            name='id',
        ),
        migrations.AddField(
            model_name='checkmask',
            name='mid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
