# Generated by Django 2.2.6 on 2020-06-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0011_checkmask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkmask',
            new_name='checkmaskk',
        ),
    ]
