# Generated by Django 2.2.6 on 2020-06-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0012_auto_20200619_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkmask',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('d_image', models.ImageField(upload_to='detected')),
            ],
        ),
        migrations.DeleteModel(
            name='checkmaskk',
        ),
    ]
