# Generated by Django 2.2.6 on 2020-06-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0013_auto_20200619_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkmask',
        ),
    ]
